# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elevation_tile_downloader/ui/raw/elevation_tile_downloader_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ElevationTileDownloaderDialogBase(object):
    def setupUi(self, ElevationTileDownloaderDialogBase):
        ElevationTileDownloaderDialogBase.setObjectName("ElevationTileDownloaderDialogBase")
        ElevationTileDownloaderDialogBase.resize(400, 221)
        self.verticalLayoutWidget = QtWidgets.QWidget(ElevationTileDownloaderDialogBase)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(29, 9, 341, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layer_choice = QgsMapLayerComboBox(self.verticalLayoutWidget)
        self.layer_choice.setObjectName("layer_choice")
        self.verticalLayout_2.addWidget(self.layer_choice)
        self.output_dir = QgsFileWidget(self.verticalLayoutWidget)
        self.output_dir.setStorageMode(QgsFileWidget.GetDirectory)
        self.output_dir.setOptions(QtWidgets.QFileDialog.ShowDirsOnly)
        self.output_dir.setObjectName("output_dir")
        self.verticalLayout_2.addWidget(self.output_dir)
        self.add_to_map = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.add_to_map.setObjectName("add_to_map")
        self.verticalLayout_2.addWidget(self.add_to_map)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ElevationTileDownloaderDialogBase)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 170, 195, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_box = QtWidgets.QDialogButtonBox(self.horizontalLayoutWidget)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout.addWidget(self.button_box)
        self.download = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.download.setObjectName("download")
        self.horizontalLayout.addWidget(self.download)

        self.retranslateUi(ElevationTileDownloaderDialogBase)
        self.button_box.accepted.connect(ElevationTileDownloaderDialogBase.accept)
        self.button_box.rejected.connect(ElevationTileDownloaderDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(ElevationTileDownloaderDialogBase)

    def retranslateUi(self, ElevationTileDownloaderDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ElevationTileDownloaderDialogBase.setWindowTitle(_translate("ElevationTileDownloaderDialogBase", "Elevation Tile Downloader"))
        self.add_to_map.setText(_translate("ElevationTileDownloaderDialogBase", "add downloaded tiles to map"))
        self.download.setText(_translate("ElevationTileDownloaderDialogBase", "Download"))
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
