# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgis/examples/elevation_tile_downloader/gui/tile_downloader_dlg_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_ElevationTileDownloaderDialogBase(object):
    def setupUi(self, ElevationTileDownloaderDialogBase):
        ElevationTileDownloaderDialogBase.setObjectName(
            "ElevationTileDownloaderDialogBase"
        )
        ElevationTileDownloaderDialogBase.resize(400, 134)
        self.verticalLayout = QtWidgets.QVBoxLayout(
            ElevationTileDownloaderDialogBase
        )
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(ElevationTileDownloaderDialogBase)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.label
        )
        self.label_2 = QtWidgets.QLabel(ElevationTileDownloaderDialogBase)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.label_2
        )
        self.output_dir = QgsFileWidget(ElevationTileDownloaderDialogBase)
        self.output_dir.setStorageMode(QgsFileWidget.GetDirectory)
        self.output_dir.setOptions(QtWidgets.QFileDialog.ShowDirsOnly)
        self.output_dir.setObjectName("output_dir")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.output_dir
        )
        self.layer_choice = QgsMapLayerComboBox(
            ElevationTileDownloaderDialogBase
        )
        self.layer_choice.setObjectName("layer_choice")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.layer_choice
        )
        self.verticalLayout.addLayout(self.formLayout_2)
        self.button_box = QtWidgets.QDialogButtonBox(
            ElevationTileDownloaderDialogBase
        )
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(ElevationTileDownloaderDialogBase)
        self.button_box.accepted.connect(
            ElevationTileDownloaderDialogBase.accept
        )
        self.button_box.rejected.connect(
            ElevationTileDownloaderDialogBase.reject
        )
        QtCore.QMetaObject.connectSlotsByName(
            ElevationTileDownloaderDialogBase
        )

    def retranslateUi(self, ElevationTileDownloaderDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ElevationTileDownloaderDialogBase.setWindowTitle(
            _translate(
                "ElevationTileDownloaderDialogBase",
                "Elevation Tile Downloader",
            )
        )
        self.label.setText(
            _translate("ElevationTileDownloaderDialogBase", "Cllip Layer")
        )
        self.label_2.setText(
            _translate("ElevationTileDownloaderDialogBase", "Output Directory")
        )


from qgsfilewidget import QgsFileWidget  # noqa: E402
from qgsmaplayercombobox import QgsMapLayerComboBox  # noqa: E402
